import Head from "next/head";
import Footer from "../../components/footer/footer";
import FormLogin from "../../components/form/FormLogin";
import Header from "../../components/header/header";
import styles from "../../styles/Login.module.css"

export default function Login() {
    return (
        <div className={styles.container}>
		<Head>
			<title>Create Next App</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
			<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous"></link>
		</Head>

      	<main className={styles.main}>
		  	<Header />
                <FormLogin />
			
		</main>
        <Footer />
    </div>
    )
}