import Head from "next/head";
import CardsList from "../components/cards/CardsList";
import Header from "../components/header/header";
import styles from "../styles/Home.module.css";

export default function Home() {

	const cardsHomeInfos = {
		program: {title: "programme", button_title: "en savoir plus", link: "/program"},
		players: {title: "les joueurs", button_title: "en savoir plus", link: "/players"}
	}

	const cardsHome = [
		cardsHomeInfos.program,
		cardsHomeInfos.players
	]

  return (
    <div className={styles.container}>
		<Head>
			<title>Create Next App</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

      	<main className={styles.main}>
		  	<Header />
		    <div className={styles.container_img_header}>
				<img className={styles.img_header} src="/images/bgheader.jpg" />
				<img className={styles.logo} src="/images/logo.png" />
			</div>
			<section className={styles.section_home} id="home">
				<div className={styles.container_title}>
					<h1 className={styles.main_title}>5e edition</h1>
					<p className={styles.sub_title}>du 15 au 21 mai 2022</p>
				</div>
				<CardsList cards={cardsHome} />
			</section>
			<section id="news">
				<div className={styles.container_title}>
					<h1 className={styles.main_title}>actualité</h1>
				</div>
			</section>
		</main>
    </div>
  );
}
