import Head from "next/head";
import Link from "next/link";
import CardsList from "../components/cards/CardsList";
import CardNewsList from "../components/cards/CardsNewsList";
import TicketsList from "../components/cards/TicketsList";
import Footer from "../components/footer/footer";
import Header from "../components/header/header";
import styles from "../styles/Home.module.css";

export default function Home() {
	//<a href="http://www.onlinewebfonts.com">oNline Web Fonts</a>
	
	const cardsHomeInfos = {
		program: {title: "programme", button_title: "en savoir plus", link: "/program"},
		players: {title: "les joueurs", button_title: "en savoir plus", link: "/players"}
	}

	const cardsNewsInfos = {
		news1: {image: "/images/news1.jpg", title: "Les dates de l'édition 2022 sont connues!", text:"L'Open Parc Auvergne-Rhône-Alpes est qualifié comme 'un des plus beaux tournois ATP 250, après avoir connu quatre premières éditions de très haut niveau en accueillant un plateau de joueurs internationaux extrêmement relevé comme par exemple : Stefanos TSITSIPAS, Jo-Wilfried TSONGA, Dominic THIEM, Gaël MONFILS, Juan Martin DEL POTRO, Milos RAONIC, Nick KYRGIOS, Denis SHAPOVALOV, Richard GASQUET, Felix AUGER-ALIASSIME …", link: "/news"},
		news2: {image: "/images/news2.jpg", title: "La billetterie 2022 est ouverte!", text: "A quelques jours des fêtes de fin d’année, nous avons le plaisir de vous annoncer l’ouverture de la billetterie grand public de la 4ème édition de l’Open Parc Auvergne-Rhône-Alpes, qui se déroulera du 16 au 23 mai 2020", link: "/news"},
		news3: {image: "/images/news3.jpg", title: "Dimanche 23 Mai - finales", text: "On s’attendait à un immense combat. Mais on savait également que Stefanos Tsitsipas était très en forme cette semaine. Dans un court central rempli à sa capacité d’accueil maximum, sous un soleil de plomb, le grec a tenu son rang de tête de série n°2 pour décrocher le septième titre de sa carrière à l’Open Parc Auvergne-Rhône-Alpes. Le numéro 5 mondial a dominé Cameron Norrie en deux manches (6-3, 6-3).", link: "/news"}
	}

	const cardsHome = [
		cardsHomeInfos.program,
		cardsHomeInfos.players
	]

	const cardsNews = [
		cardsNewsInfos.news2,
		cardsNewsInfos.news1,
		cardsNewsInfos.news3
	]

	const refsHeader = {
		home: "#home",
		news: "#news",
		tickets: "#tickets"
	}

  return (
    <div className={styles.container}>
		<Head>
			<title>Create Next App</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
			<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous"></link>
		</Head>

      	<main className={styles.main}>
		  	<Header refs={refsHeader} />
		    <div className={styles.container_img_header}>
				<img className={styles.img_header} src="/images/bgheader.jpg" />
				<img className={styles.logo} src="/images/logo.png" />
			</div>
			
			<section className={styles.section_home} id="home">
				<div className={styles.container_title}>
					<h1 className={styles.main_title}>5e edition</h1>
					<p className={styles.sub_title}>du 15 au 21 mai 2022</p>
				</div>
				<CardsList cards={cardsHome} />
			</section>

			<section className={styles.section_news} id="news">
				<div className={styles.container_title}>
					<h1 className={styles.main_title}>actualités</h1>
				</div>
				<CardNewsList cards={cardsNews}/>
			</section>

			<section className={styles.section_ticketing} id="tickets">
				<div className={styles.container_title}>
					<Link href="/ticketing">
						<a><h1 className={styles.main_title}>billetterie</h1></a>
					</Link>
				</div>
				<TicketsList />
			</section>
			<Footer />
		</main>
    </div>
  );
}
